### ISSUE TITLE
Can't build gentoo-chroot

### ISSUE THREAD

**Issue by bolzerrr** [MasterRoot24/spksrc#1]
Hi,

i just tried to build the gentoo-chroot spk but it fails:
```
make arch-evansport
===> Building package for arch evansport
make[1]: Entering directory /usr/local/src/spksrc2/spk/gentoo-chroot' ===> Striping binaries and libraries of gentoo-chroot wget -nv -c -O /usr/local/src/spksrc2/spk/gentoo-chroot/work-evansport/stage3-i686-20141209.tar.bz2 http://distfiles.gentoo.org/releases/x86/autobuilds/20141209/stage3-i686-20141209.tar.bz2 195643340 make[1]: *** [gentoo-chroot_extra_install] Error 4 make[1]: Leaving directory/usr/local/src/spksrc2/spk/gentoo-chroot'
make: [arch-evansport] Error 2 (ignored)
```

If you need any further information let me know.

Regards

**Comment by MasterRoot24** [comment]
I'll take a look into this ASAP

**Comment by MasterRoot24** [comment]
This issue was caused by a change in the format of the latest stage3 file in the Gentoo mirrors. I've pushed a fix for this now and I can successfully build for `arch-evansport`.

Also note: I've already submitted a pre-built `.spk` [here](https://github.com/MasterRoot24/spksrc/releases/tag/13.0-1).
